//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDS.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class LBM : global::System.Configuration.ApplicationSettingsBase {
        
        private static LBM defaultInstance = ((LBM)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LBM())));
        
        public static LBM Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wmw")]
        public string Middleware {
            get {
                return ((string)(this["Middleware"]));
            }
            set {
                this["Middleware"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\LBMLogs\\")]
        public string MamaLogPath {
            get {
                return ((string)(this["MamaLogPath"]));
            }
            set {
                this["MamaLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ronin")]
        public string TransportName {
            get {
                return ((string)(this["TransportName"]));
            }
            set {
                this["TransportName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WOMBAT")]
        public string DictionarySourceSymbolNamespace {
            get {
                return ((string)(this["DictionarySourceSymbolNamespace"]));
            }
            set {
                this["DictionarySourceSymbolNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMamaLog {
            get {
                return ((bool)(this["EnableMamaLog"]));
            }
            set {
                this["EnableMamaLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public uint IdelTimeBetweenRetries {
            get {
                return ((uint)(this["IdelTimeBetweenRetries"]));
            }
            set {
                this["IdelTimeBetweenRetries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxRetries {
            get {
                return ((int)(this["MaxRetries"]));
            }
            set {
                this["MaxRetries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ThrottleDefault {
            get {
                return ((int)(this["ThrottleDefault"]));
            }
            set {
                this["ThrottleDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ThrottleInitial {
            get {
                return ((int)(this["ThrottleInitial"]));
            }
            set {
                this["ThrottleInitial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ThrottleRecap {
            get {
                return ((int)(this["ThrottleRecap"]));
            }
            set {
                this["ThrottleRecap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseChangeNotificationRate {
            get {
                return ((bool)(this["UseChangeNotificationRate"]));
            }
            set {
                this["UseChangeNotificationRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ChangeNotificationRate {
            get {
                return ((int)(this["ChangeNotificationRate"]));
            }
            set {
                this["ChangeNotificationRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLBMLog {
            get {
                return ((bool)(this["EnableLBMLog"]));
            }
            set {
                this["EnableLBMLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubscriptionUseWaitForSymbol {
            get {
                return ((bool)(this["SubscriptionUseWaitForSymbol"]));
            }
            set {
                this["SubscriptionUseWaitForSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MamaMsgQueueLimitPerSymbol {
            get {
                return ((int)(this["MamaMsgQueueLimitPerSymbol"]));
            }
            set {
                this["MamaMsgQueueLimitPerSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTA,NASDAQ,TDDS,GIDS,CME,CME-CBOT,CME-KCBOT,CME-NYMEX,CME-COMEX-CME-MGEX,ICE,ACTI" +
            "V,ONEC,CFE,OPRA,OPRANBBO,REUTERS,MDI")]
        public string SubscriptionSourceRange {
            get {
                return ((string)(this["SubscriptionSourceRange"]));
            }
            set {
                this["SubscriptionSourceRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALL")]
        public string SubscriptionSymbolRange {
            get {
                return ((string)(this["SubscriptionSymbolRange"]));
            }
            set {
                this["SubscriptionSymbolRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int SubscriptionTimeGap {
            get {
                return ((int)(this["SubscriptionTimeGap"]));
            }
            set {
                this["SubscriptionTimeGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int BookDepthLimit {
            get {
                return ((int)(this["BookDepthLimit"]));
            }
            set {
                this["BookDepthLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTA,NASDAQ,TDDS,GIDS")]
        public string StockSources {
            get {
                return ((string)(this["StockSources"]));
            }
            set {
                this["StockSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICE,CME,CME-CBOT,CME-KCBOT,CME-NYMEX,CME-COMEX-CME-MGEX")]
        public string FutureSources {
            get {
                return ((string)(this["FutureSources"]));
            }
            set {
                this["FutureSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPRA,OPRANBBO")]
        public string OptionSources {
            get {
                return ((string)(this["OptionSources"]));
            }
            set {
                this["OptionSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetRecoverGaps {
            get {
                return ((bool)(this["SetRecoverGaps"]));
            }
            set {
                this["SetRecoverGaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\WombatPath\\E")]
        public string WombatPath {
            get {
                return ((string)(this["WombatPath"]));
            }
            set {
                this["WombatPath"] = value;
            }
        }
    }
}
