#include "RomReject.h"

CRomReject::CRomReject(const CCsv& msg, std::string& reason): CCsv(msg)
{
  char cmd = ROMVALUE::COMMAND_ORDER;
  GetAt(ROMFIELDS::CSV_COMMAND, cmd);
	SetAt(ROMFIELDS::CSV_TEXT, reason);

	if (cmd == ROMVALUE::COMMAND_ORDER)
	{
		SetAt(ROMFIELDS::CSV_COMMAND, ROMVALUE::COMMAND_STATUS);
		SetAt(ROMFIELDS::CSV_STATUS, ROMVALUE::STATUS_ORDERREJECTED);
	}
	else if (cmd == ROMVALUE::COMMAND_CANCEL ||
			 cmd == ROMVALUE::COMMAND_CANCELS)
	{
		SetAt(ROMFIELDS::CSV_COMMAND, ROMVALUE::COMMAND_STATUS);
		SetAt(ROMFIELDS::CSV_STATUS, ROMVALUE::STATUS_CANCELREJECTED);
	}
	else if (cmd == ROMVALUE::COMMAND_REPLACE)
	{
		SetAt(ROMFIELDS::CSV_COMMAND, ROMVALUE::COMMAND_STATUS);
		SetAt(ROMFIELDS::CSV_STATUS, ROMVALUE::STATUS_REPLACEREJECTED);
	}
	else
	{
		SetAt(ROMFIELDS::CSV_COMMAND, ROMVALUE::COMMAND_REJECT);
	}
}

CRomReject::~CRomReject(void)
{

}


