//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRLabMDS.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class SRLab : global::System.Configuration.ApplicationSettingsBase {
        
        private static SRLab defaultInstance = ((SRLab)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SRLab())));
        
        public static SRLab Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\SRLabConfig\\")]
        public string Configlocation {
            get {
                return ((string)(this["Configlocation"]));
            }
            set {
                this["Configlocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ronin-mc-client-allfeeds.xml")]
        public string ConfigFile {
            get {
                return ((string)(this["ConfigFile"]));
            }
            set {
                this["ConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Depth {
            get {
                return ((int)(this["Depth"]));
            }
            set {
                this["Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.103.102.29")]
        public string LocalIP {
            get {
                return ((string)(this["LocalIP"]));
            }
            set {
                this["LocalIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FireLevel1Only {
            get {
                return ((bool)(this["FireLevel1Only"]));
            }
            set {
                this["FireLevel1Only"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LastValue {
            get {
                return ((bool)(this["LastValue"]));
            }
            set {
                this["LastValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DelayMCJoin {
            get {
                return ((bool)(this["DelayMCJoin"]));
            }
            set {
                this["DelayMCJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WARN")]
        public string LogLevel {
            get {
                return ((string)(this["LogLevel"]));
            }
            set {
                this["LogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string MaxLogSize {
            get {
                return ((string)(this["MaxLogSize"]));
            }
            set {
                this["MaxLogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MDRCClientSessionMgr")]
        public string SMType {
            get {
                return ((string)(this["SMType"]));
            }
            set {
                this["SMType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTA,NASDAQ,OPRANBBO")]
        public string SMNames {
            get {
                return ((string)(this["SMNames"]));
            }
            set {
                this["SMNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSRLabLog {
            get {
                return ((bool)(this["EnableSRLabLog"]));
            }
            set {
                this["EnableSRLabLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSRLabPerformanceLog {
            get {
                return ((bool)(this["EnableSRLabPerformanceLog"]));
            }
            set {
                this["EnableSRLabPerformanceLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BusyWait {
            get {
                return ((bool)(this["BusyWait"]));
            }
            set {
                this["BusyWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SubscriptionTimeGap {
            get {
                return ((int)(this["SubscriptionTimeGap"]));
            }
            set {
                this["SubscriptionTimeGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ChangeNotificationRate {
            get {
                return ((int)(this["ChangeNotificationRate"]));
            }
            set {
                this["ChangeNotificationRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseChangeNotificationRate {
            get {
                return ((bool)(this["UseChangeNotificationRate"]));
            }
            set {
                this["UseChangeNotificationRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubscriptionUseWaitForSymbol {
            get {
                return ((bool)(this["SubscriptionUseWaitForSymbol"]));
            }
            set {
                this["SubscriptionUseWaitForSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SubscribeWithSource {
            get {
                return ((bool)(this["SubscribeWithSource"]));
            }
            set {
                this["SubscribeWithSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LineTimeHourOffset {
            get {
                return ((int)(this["LineTimeHourOffset"]));
            }
            set {
                this["LineTimeHourOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LineTimeMinOffset {
            get {
                return ((int)(this["LineTimeMinOffset"]));
            }
            set {
                this["LineTimeMinOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LineTimeSecOffset {
            get {
                return ((int)(this["LineTimeSecOffset"]));
            }
            set {
                this["LineTimeSecOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CME,CME-CBOT,CME-MGEX,CME-NYMEX")]
        public string CMEExchangeList {
            get {
                return ((string)(this["CMEExchangeList"]));
            }
            set {
                this["CMEExchangeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTA,NASDAQ,OPRANBBO")]
        public string SubscriptionSourceRange {
            get {
                return ((string)(this["SubscriptionSourceRange"]));
            }
            set {
                this["SubscriptionSourceRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALL")]
        public string SubscriptionSymbolRange {
            get {
                return ((string)(this["SubscriptionSymbolRange"]));
            }
            set {
                this["SubscriptionSymbolRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTA,NASDAQ")]
        public string StockSources {
            get {
                return ((string)(this["StockSources"]));
            }
            set {
                this["StockSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICE,CME,CME-CBOT,CME-MGEX,CME-NYMEX")]
        public string FutureSources {
            get {
                return ((string)(this["FutureSources"]));
            }
            set {
                this["FutureSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPRA,OPRANBBO")]
        public string OptionSources {
            get {
                return ((string)(this["OptionSources"]));
            }
            set {
                this["OptionSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string CTAPrimary {
            get {
                return ((string)(this["CTAPrimary"]));
            }
            set {
                this["CTAPrimary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public string NASDAQPrimay {
            get {
                return ((string)(this["NASDAQPrimay"]));
            }
            set {
                this["NASDAQPrimay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConvertOPRA {
            get {
                return ((bool)(this["ConvertOPRA"]));
            }
            set {
                this["ConvertOPRA"] = value;
            }
        }
    }
}
