//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROC.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Override : global::System.Configuration.ApplicationSettingsBase {
        
        private static Override defaultInstance = ((Override)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Override())));
        
        public static Override Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ByPassROM {
            get {
                return ((bool)(this["ByPassROM"]));
            }
            set {
                this["ByPassROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ByPassRDS {
            get {
                return ((bool)(this["ByPassRDS"]));
            }
            set {
                this["ByPassRDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPRANBBOTEST")]
        public string OverrideNBBO {
            get {
                return ((string)(this["OverrideNBBO"]));
            }
            set {
                this["OverrideNBBO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOverridNBBO {
            get {
                return ((bool)(this["UseOverridNBBO"]));
            }
            set {
                this["UseOverridNBBO"] = value;
            }
        }
    }
}
