//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROC.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Path : global::System.Configuration.ApplicationSettingsBase {
        
        private static Path defaultInstance = ((Path)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Path())));
        
        public static Path Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\Logs")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\Orders")]
        public string OrderPath {
            get {
                return ((string)(this["OrderPath"]));
            }
            set {
                this["OrderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\Trades")]
        public string TradePath {
            get {
                return ((string)(this["TradePath"]));
            }
            set {
                this["TradePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\Profiles")]
        public string ProfilePath {
            get {
                return ((string)(this["ProfilePath"]));
            }
            set {
                this["ProfilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\Positions")]
        public string PositionPath {
            get {
                return ((string)(this["PositionPath"]));
            }
            set {
                this["PositionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\Profiles\\Symbols")]
        public string SymbolSettingPath {
            get {
                return ((string)(this["SymbolSettingPath"]));
            }
            set {
                this["SymbolSettingPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\Profiles\\Settings")]
        public string SettingPath {
            get {
                return ((string)(this["SettingPath"]));
            }
            set {
                this["SettingPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\CSVConfig")]
        public string CSVConfigPath {
            get {
                return ((string)(this["CSVConfigPath"]));
            }
            set {
                this["CSVConfigPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\OptionConfig")]
        public string OptionConfigPath {
            get {
                return ((string)(this["OptionConfigPath"]));
            }
            set {
                this["OptionConfigPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\Profiles\\QuickButtonConfig")]
        public string QuickButtonConfigPath {
            get {
                return ((string)(this["QuickButtonConfigPath"]));
            }
            set {
                this["QuickButtonConfigPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\FutureConfig")]
        public string FutureConfigPath {
            get {
                return ((string)(this["FutureConfigPath"]));
            }
            set {
                this["FutureConfigPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\SubscriptionCache")]
        public string SubscriptionCachePath {
            get {
                return ((string)(this["SubscriptionCachePath"]));
            }
            set {
                this["SubscriptionCachePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\clangan\\Applications\\ROC\\OrderTypeConfig")]
        public string OrderTypeConfigPath {
            get {
                return ((string)(this["OrderTypeConfigPath"]));
            }
            set {
                this["OrderTypeConfigPath"] = value;
            }
        }
    }
}
