//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROC.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ROC : global::System.Configuration.ApplicationSettingsBase {
        
        private static ROC defaultInstance = ((ROC)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ROC())));
        
        public static ROC Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ARCA,INET,NYSE,BATS,EDG")]
        public string ExchangesSupportExtendedMarketOrderType {
            get {
                return ((string)(this["ExchangesSupportExtendedMarketOrderType"]));
            }
            set {
                this["ExchangesSupportExtendedMarketOrderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ARCA,INET,NYSE,BATS,EDG")]
        public string ExchangesSupportExtendedLimitOrderType {
            get {
                return ((string)(this["ExchangesSupportExtendedLimitOrderType"]));
            }
            set {
                this["ExchangesSupportExtendedLimitOrderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseGroupSubscription {
            get {
                return ((bool)(this["UseGroupSubscription"]));
            }
            set {
                this["UseGroupSubscription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int BookDepthLimit {
            get {
                return ((int)(this["BookDepthLimit"]));
            }
            set {
                this["BookDepthLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MemoryFlushInterval {
            get {
                return ((int)(this["MemoryFlushInterval"]));
            }
            set {
                this["MemoryFlushInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public long MemoryFlushLimit {
            get {
                return ((long)(this["MemoryFlushLimit"]));
            }
            set {
                this["MemoryFlushLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusPlotList {
            get {
                return ((bool)(this["EnableAutoFocusPlotList"]));
            }
            set {
                this["EnableAutoFocusPlotList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusWatchList {
            get {
                return ((bool)(this["EnableAutoFocusWatchList"]));
            }
            set {
                this["EnableAutoFocusWatchList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusOrders {
            get {
                return ((bool)(this["EnableAutoFocusOrders"]));
            }
            set {
                this["EnableAutoFocusOrders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusPositions {
            get {
                return ((bool)(this["EnableAutoFocusPositions"]));
            }
            set {
                this["EnableAutoFocusPositions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusBatchTicket {
            get {
                return ((bool)(this["EnableAutoFocusBatchTicket"]));
            }
            set {
                this["EnableAutoFocusBatchTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusFutureTicket {
            get {
                return ((bool)(this["EnableAutoFocusFutureTicket"]));
            }
            set {
                this["EnableAutoFocusFutureTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusOptionTicket {
            get {
                return ((bool)(this["EnableAutoFocusOptionTicket"]));
            }
            set {
                this["EnableAutoFocusOptionTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusQuickTicket {
            get {
                return ((bool)(this["EnableAutoFocusQuickTicket"]));
            }
            set {
                this["EnableAutoFocusQuickTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusStockTicket {
            get {
                return ((bool)(this["EnableAutoFocusStockTicket"]));
            }
            set {
                this["EnableAutoFocusStockTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusTrades {
            get {
                return ((bool)(this["EnableAutoFocusTrades"]));
            }
            set {
                this["EnableAutoFocusTrades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusAutoSpreadTicket {
            get {
                return ((bool)(this["EnableAutoFocusAutoSpreadTicket"]));
            }
            set {
                this["EnableAutoFocusAutoSpreadTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NYSE,GLBX,GLOBEX")]
        public string ExchangesSupportStopOrderType {
            get {
                return ((string)(this["ExchangesSupportStopOrderType"]));
            }
            set {
                this["ExchangesSupportStopOrderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GLBX,GLOBEX")]
        public string ExchangesSupportLimitStopOrderType {
            get {
                return ((string)(this["ExchangesSupportLimitStopOrderType"]));
            }
            set {
                this["ExchangesSupportLimitStopOrderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ARCA,INET,BATS,EDG")]
        public string ExchangesSupportPegMktOrderType {
            get {
                return ((string)(this["ExchangesSupportPegMktOrderType"]));
            }
            set {
                this["ExchangesSupportPegMktOrderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ARCA,INET,BATS,EDG")]
        public string ExchangesSupportPegPriOrderType {
            get {
                return ((string)(this["ExchangesSupportPegPriOrderType"]));
            }
            set {
                this["ExchangesSupportPegPriOrderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INET,BATS,EDG")]
        public string ExchangesSupportPegMidOrderType {
            get {
                return ((string)(this["ExchangesSupportPegMidOrderType"]));
            }
            set {
                this["ExchangesSupportPegMidOrderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LargeScreenSize {
            get {
                return ((bool)(this["LargeScreenSize"]));
            }
            set {
                this["LargeScreenSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLevel2AsDefault {
            get {
                return ((bool)(this["ShowLevel2AsDefault"]));
            }
            set {
                this["ShowLevel2AsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowQuickTicketAsDefault {
            get {
                return ((bool)(this["ShowQuickTicketAsDefault"]));
            }
            set {
                this["ShowQuickTicketAsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INET")]
        public string ExchangesSupportImbalanceOnlyType {
            get {
                return ((string)(this["ExchangesSupportImbalanceOnlyType"]));
            }
            set {
                this["ExchangesSupportImbalanceOnlyType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoFocusMarketDataBatchTicket {
            get {
                return ((bool)(this["EnableAutoFocusMarketDataBatchTicket"]));
            }
            set {
                this["EnableAutoFocusMarketDataBatchTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableQuickTicketAutoCenter {
            get {
                return ((bool)(this["EnableQuickTicketAutoCenter"]));
            }
            set {
                this["EnableQuickTicketAutoCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public long QuickTicketAutoCenterRange {
            get {
                return ((long)(this["QuickTicketAutoCenterRange"]));
            }
            set {
                this["QuickTicketAutoCenterRange"] = value;
            }
        }
    }
}
