//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROC.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class SOUND : global::System.Configuration.ApplicationSettingsBase {
        
        private static SOUND defaultInstance = ((SOUND)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SOUND())));
        
        public static SOUND Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Sounds\\CLICK.WAV")]
        public string Open {
            get {
                return ((string)(this["Open"]));
            }
            set {
                this["Open"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Sounds\\CASHREG.WAV")]
        public string Filled {
            get {
                return ((string)(this["Filled"]));
            }
            set {
                this["Filled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Sounds\\EXPLODE.WAV")]
        public string Rejected {
            get {
                return ((string)(this["Rejected"]));
            }
            set {
                this["Rejected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Sounds\\EXPLODE.WAV")]
        public string Canceled {
            get {
                return ((string)(this["Canceled"]));
            }
            set {
                this["Canceled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Sounds\\CASHREG.WAV")]
        public string FilledAndCanceled {
            get {
                return ((string)(this["FilledAndCanceled"]));
            }
            set {
                this["FilledAndCanceled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Sounds\\CASHREG.WAV")]
        public string PartiallyFilled {
            get {
                return ((string)(this["PartiallyFilled"]));
            }
            set {
                this["PartiallyFilled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Sounds\\CLICK.WAV")]
        public string Replaced {
            get {
                return ((string)(this["Replaced"]));
            }
            set {
                this["Replaced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableOpen {
            get {
                return ((bool)(this["EnableOpen"]));
            }
            set {
                this["EnableOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableFilled {
            get {
                return ((bool)(this["EnableFilled"]));
            }
            set {
                this["EnableFilled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRejected {
            get {
                return ((bool)(this["EnableRejected"]));
            }
            set {
                this["EnableRejected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCanceled {
            get {
                return ((bool)(this["EnableCanceled"]));
            }
            set {
                this["EnableCanceled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnablePartiallyFilled {
            get {
                return ((bool)(this["EnablePartiallyFilled"]));
            }
            set {
                this["EnablePartiallyFilled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableReplaced {
            get {
                return ((bool)(this["EnableReplaced"]));
            }
            set {
                this["EnableReplaced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableFilledAndCanceled {
            get {
                return ((bool)(this["EnableFilledAndCanceled"]));
            }
            set {
                this["EnableFilledAndCanceled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Sounds\\CASHREG.WAV")]
        public string AutoSpreadPartiallyFilled {
            get {
                return ((string)(this["AutoSpreadPartiallyFilled"]));
            }
            set {
                this["AutoSpreadPartiallyFilled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableAutoSpreadPartiallyFilled {
            get {
                return ((bool)(this["EnableAutoSpreadPartiallyFilled"]));
            }
            set {
                this["EnableAutoSpreadPartiallyFilled"] = value;
            }
        }
    }
}
